name: Run integration tests
description: Start SonarQube and run the integration test suite.

inputs:
  sonarqube-version:
    description: SonarQube Community Build version to test against.
    default: 26.9.0.129388

runs:
  using: composite
  steps:
    - name: Cache SonarQube
      uses: SonarSource/gh-action_cache@v1
      with:
        path: .sonarqube_cache/
        key: sonarqube-${{ runner.os }}-zip-${{ inputs.sonarqube-version }}

    - name: Install mise and tools
      uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
      with:
        version: 2026.10.3
        tool_versions: |
          python 3.12.1
          java temurin-21
        experimental: true

    - name: Configure poetry
      uses: SonarSource/ci-github-actions/config-poetry@v1
      with:
        artifactory-reader-role: private-reader

    - name: Execute the integration tests
      shell: bash
      env:
        SONARQUBE_VERSION: ${{ inputs.sonarqube-version }}
      run: ./scripts/run_its.sh
