name: sonar-pre-release
# This workflow is triggered when publishing a new GitHub pre-release
on:
  release:
    types:
      - prereleased

jobs:
  prerelease:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@v5
    with:
      publishToTestPyPI: true
      skipPythonReleasabilityChecks: true
