name: sonar-release
# This workflow is triggered when publishing a new GitHub release
on:
  release:
    types:
      - published

jobs:
  prerelease:
    if: "github.event.release.prerelease"
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@22cded87a58ad248b24669e05da2fb34ce7c699e # 5.19.0
    with:
      publishToTestPyPI: true
      skipPythonReleasabilityChecks: true
  release:
    if: "!github.event.release.prerelease"
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@22cded87a58ad248b24669e05da2fb34ce7c699e # 5.19.0
    with:
      publishToPyPI: true
      skipPythonReleasabilityChecks: true
